- README.md
We removed the routers, but the README still directs people to use them.
Oops. This removes them and replaces them with some, admittedly vague,
guidance instead.
Fixes #40.
> Fix README references to routers.

- tfprotov5/state.go
The tfprotov5.RawState type exposes state through a []byte containing
JSON when upgrading resource state with the UpgradeResourceState RPC. We
had not surfaced any JSON parsing or decoding in the exported API, so
providers would need to parse the JSON themselves.
To solve this, we use the same Unmarshal interface we use for parsing
JSON from DynamicValues, letting users receive a tftypes.Value from a
RawState without needing to worry about encoding... mostly.
There is one hitch. The Flatmap syntax doesn't have a canonical
translation (yet? As far as I know) to Terraform's type system. So we
sidestep that by returning an error, for the moment. In the future, we
could conceivably institute a mapping, though I'm not convinced it's a
good idea to, given the number of assumptions that would …
> Add the ability to unmarshal RawState.

- tfprotov5/server/server.go
This should fix #45.
Note the corresponding code in the SDK gRPC server, which was missed out when we ported the `stopCh` implementation to terraform-plugin-go: https://github.com/hashicorp/terraform-plugin-sdk/blob/master/helper/schema/grpc_provider.go#L29
I'm not completely happy with this yet because I don't have a consistent reproduction case; this code (`server.Stop`) is not run every time a Ctrl-C is issued during a `terraform apply`. Leaving this here so we can either agree it's a reasonable change and merge it, or decide to investigate further.
> initialise stopCh before using

- README.md
README was pointing to master in a few places, but we use main.
> Fix README links.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Instead of relying on the user having `jq` installed, use a more
idiomatic method to retrieve the module's version in our issue template,
relying only on the `go` command.
> Use go list to get module version in issue templates.

- .changelog/58.txt
- tfprotov5/dynamic_value_json.go
- tfprotov5/dynamic_value_msgpack.go
- tfprotov5/tftypes/list.go
- tfprotov5/tftypes/map.go
- tfprotov5/tftypes/object.go
- tfprotov5/tftypes/primitive.go
- tfprotov5/tftypes/set.go
- tfprotov5/tftypes/tuple.go
- tfprotov5/tftypes/value.go
- tfprotov5/tftypes/value_msgpack.go
Add a method to expose the tftypes.Type associated with a tftypes.Value.
This is necessary because tftypes.Value.Is is not always able to
reconstruct a type from comparison alone; for example, reconstructing
what types a map, object, list, set, or tuple uses when its
tftypes.Value is the unknown value is impossible.
But we can make it so people can't directly compare them with ==, which
we don't want them doing (we want them to use Is instead) by embedding a
`_ []struct{}` in each type, which cannot be compared and prevents the
types from being compared, raising a compile time error.
This does mean our primitive types are now structs, and therefore cannot
be constants, which is sad. In theory, someone could overwrite them and
change the output, but the amount of shenanigans one can get up …
> Expose Types of tftypes.Values.

- .changelog/62.txt
- .circleci/config.yml
- go.mod
As Go 1.16 is out, our latest supported version is now Go 1.15. Upgrade
to it, and add Go 1.16 to our CI testing matrix.
> Upgrade to Go 1.15.

- .changelog/60.txt
- tfprotov5/tftypes/attribute_path.go
- tfprotov5/tftypes/attribute_path_test.go
- tfprotov5/tftypes/diff.go
- tfprotov5/tftypes/diff_test.go
- tfprotov5/tftypes/list.go
- tfprotov5/tftypes/map.go
- tfprotov5/tftypes/object.go
- tfprotov5/tftypes/set.go
- tfprotov5/tftypes/tuple.go
- tfprotov5/tftypes/value.go
- tfprotov5/tftypes/value_msgpack.go
- tfprotov5/tftypes/value_test.go
- tfprotov5/tftypes/walk.go
- tfprotov5/tftypes/walk_test.go
This turned into a massive commit. I'm really sorry.
I set out to implement Walk and Transform. Walk was simple enough.
Transform was implemented quickly and easily enough. And then I tried to
test it.
Testing Transform reasonably necessitated all the other changes you see
here:
* We needed to be able to Diff Values to be able to express changes
between Values so we could test that Transform made the changes we
wanted it to.
* We needed to be able to represent AttributePaths as strings so we
could have specific, useful test output. This also entailed making
Values strings (AttributePaths can use Values as a step) and making
Types have more specific strings (aggregate types now expose the
subtypes that make up their type signature).
* In doing so, we kept accidentally overwriting our …
> Walk, Transform, Diff, Equal, and String.

- .changelog/69.txt
- tfprotov5/tftypes/value.go
- tfprotov5/tftypes/value_test.go
Calling Value.IsFullyKnown would panic if the type of the value was an
aggregate type (List, Set, Tuple, Map, or Object) and if that value
itself was null.
This adds tests to reproduce those panics and a minor change to
IsFullyKnown that prevents the panics.
> Fix panic in IsFullyKnown.

- .changelog/68.txt
- tfprotov5/internal/fromproto/attribute_path.go
- tfprotov5/internal/toproto/attribute_path.go
- tfprotov5/tftypes/attribute_path.go
- tfprotov5/tftypes/attribute_path_error.go
- tfprotov5/tftypes/attribute_path_test.go
- tfprotov5/tftypes/diff.go
- tfprotov5/tftypes/diff_test.go
- tfprotov5/tftypes/value.go
- tfprotov5/tftypes/value_msgpack.go
- tfprotov5/tftypes/value_test.go
- tfprotov5/tftypes/walk.go
- tfprotov5/tftypes/walk_test.go
Make AttributePaths into pointers everywhere, so they can be
ergonomically used with diagnostics. nil pointers are considered
equivalent to AttributePaths with no steps.
Because modifying steps on the AttributePath without defensively copying
first is now A Major Headache and makes everything awful, I made them
private. This necessitated the creation of a NewAttributePathWithSteps
so our internal code for translating between protocol and tftypes could
create the AttributePath all in one go without a bunch of unnecessary
code. I also added NewAttributePath to avoid littering
`&AttributePath{}` around our code and provider code everywhere.
This also necessitated adding a `Steps` method to AttributePaths, so
provider devs could get at the steps in a read-only fashion. `Steps` is
safe to call …
> Make AttributePaths pointers, fix AttributePathErrors.

- .changelog.tmpl
Fix the changelog template to use the `enhancement` type instead of
`improvement`, which is what all the changelog entries so far had been
using.
> Update changelog template.

- .changelog/74.txt
- tfprotov5/dynamic_value_msgpack.go
- tfprotov6/dynamic_value_msgpack.go
- tftypes/list.go
- tftypes/list_test.go
- tftypes/map.go
- tftypes/map_test.go
- tftypes/object.go
- tftypes/object_test.go
- tftypes/primitive.go
- tftypes/primitive_test.go
- tftypes/set.go
- tftypes/set_test.go
- tftypes/tuple.go
- tftypes/tuple_test.go
- tftypes/type.go
- tftypes/type_json_test.go
- tftypes/value.go
- tftypes/value_object_test.go
This is another massive PR, sorry. I tried to separate out some of the
changes, but the code kept overlapping, unfortunately.
All our Types got an Equal method, so they can be compared using go-cmp.
This was necessary to make the tests pass. As part of this, the Type
interface was refactored to include an equals() private method, which
powers the Equal and Is methods on each type.
I also fixed some periods in error messages to make golint happy.
Of course, with these new methods, there was enough logic to add tests
to each Type, so I added some tests that exercised the equality checks.
I also added, which was the main thing I was trying to do here, an
OptionalAttributes property to Objects. These are attributes that _can_
be set on an object, but are not _required_ to be.
Because …
> Implement OptionalAttributes for Objects.

- tftypes/list.go
- tftypes/map.go
- tftypes/object.go
- tftypes/set.go
- tftypes/tuple.go
- tftypes/type.go
- tftypes/value_list_test.go
- tftypes/value_map_test.go
- tftypes/value_object_test.go
- tftypes/value_set_test.go
- tftypes/value_test.go
- tftypes/value_tuple_test.go
Fix the checks that NewValue runs to ensure that a value can be used
with a Type to properly handle DynamicPseudoTypes nested in complex
types. Builds on and supersedes #76.
Should we make this part of the behavior for `.Is`? My gut says "no",
because `Is` is supposed to be about checking whether a type is
semantically similar, not that it can be used as another type. Maybe we
want a `Fulfills` method, similar to Is, that does this? I don't know
that this behavior needs to be exported, though...
Fixes a bug in #74 that would panic for complex types containing
DynamicPseudoTypes.
> Fix NewValue checks to be properly recursive

- .changelog/85.txt
- tftypes/value.go
- tftypes/value_test.go
*big.Float is a pointer type that will never really appear as anything
except a pointer. So when using code like this:
```go
var foo *big.Float
err := value.As(&foo)
```
the target of `As` is actually a **big.Float. But our code dereferences
it and calls `As` on the target of the pointer, but the target of the
pointer is actually a nil pointer.
This code fixes that by instantiating a new value for the pointer to
point to, setting the pointer to that, and then calling `As` on the new
value.
> Fix panic for Value.As(**big.Float).

- .changelog/86.txt
- tftypes/value.go
- tftypes/value_test.go
While a `Value` without a `typ` will not be returned from `NewValue` except in case of error, `Value{}` is likely to appear in consumer code from time to time, e.g. in tests, as it is the nil value of the struct. 
This PR defines an arbitrary string representation for `Value{}`. The only non-trivial question here is what it should be.
Backwards-compatible because this was previously undefined behaviour.
This PR also adds lots of tests for `Value.String()`, which had little test coverage.
> Don't panic when String() is called on nil Value{}

- .changelog/87.txt
- tftypes/attribute_path_error.go
For empty AttributePaths (paths pointing to the root of the
type/whatever) don't prefix an empty colon, prefix it with `<root>:`.
> Better formatting for root AttributePaths.

- .changelog/90.txt
- tftypes/value.go
- tftypes/value_test.go
If a non-empty tftypes.Value was compared to the empty value of a
tftypes.Value, it would cause a panic. Add tests to show the issue and
fix it.
> Fix panic in tftypes.Value.Equal.

- .changelog/105.txt
- tfprotov5/schema.go
- tfprotov6/schema.go
- tftypes/list_test.go
- tftypes/map.go
- tftypes/map_test.go
- tftypes/object.go
- tftypes/set_test.go
- tftypes/tuple_test.go
- tftypes/type.go
- tftypes/type_json_test.go
- tftypes/value.go
- tftypes/value_json.go
- tftypes/value_json_test.go
- tftypes/value_map_test.go
- tftypes/value_msgpack.go
- tftypes/value_msgpack_test.go
- tftypes/value_test.go
- tftypes/walk_test.go
Maps don't have an AttributeType in cty. They have an ElementType. In my
wayward youth of like a year ago, I decided this was A Mistake and in my
great and everlasting wisdom, I changed it to AttributeType. I think my
rationale was that elements are integer-indexed and attributes are
string-indexed.
My hubris has bitten me. This was a bad take. It makes diagnostics weird
(why am I using an ElementKeyString instead of an AttributeName if it's
an attribute?) and deviates with basically no value.
Worse, it's just... wrong. Attributes are structural in nature, like
properties in Go structs. They're defined by the provider developer.
Elements aren't structural, like Go maps. The type has no constraint on
what keys or how many keys can be used. Maps are obviously this second
thing.
This is the …
> The Great Renaming of Map.AttributeType.

- .changelog/116.txt
- tftypes/object.go
- tftypes/value_msgpack_test.go
The value of a `DynamicPseudoType` should be allowed to be either unknown or null. The check for the latter was missing and this PR adds it. Let me know if there are any more tests needed.
Solves #115
> Accept objects with DynamicPseudoType with null values

- go.mod
- go.sum
- tftypes/value.go
- tftypes/value_msgpack.go
Reference: https://github.com/vmihailenco/msgpack/compare/v4.0.4...v4.3.12
Reference: https://github.com/hashicorp/terraform/blob/2c8edfb2593a0c3cec044c1504bf1c1edd3f4a94/go.mod#L176
Migrates to Go modules compatible versioning and matches Terraform CLI dependency. ~Was not previously caught by dependabot due to the incompatible versioning.~ dependabot is not enabled. 😦 
Updated via:
```
go get github.com/vmihailenco/msgpack/v4@v4.3.12
go mod tidy
```
> deps: Bump github.com/vmihailenco/msgpack/v4@v4.3.12

- .changelog/135.txt
- README.md
- internal/logging/context.go
- internal/logging/doc.go
- internal/logging/environment_variables.go
- internal/logging/keys.go
- internal/logging/protocol.go
- internal/logging/protocol_data.go
- internal/logging/provider.go
- internal/logging/provider_test.go
- tfprotov5/tf5server/server.go
- tfprotov6/tf6server/server.go
Closes #107
This changeset refactors the `tf5server` and `tf6server` logging implementations into a shared internal package to reduce code duplication. The protocol data handling utilizes the `TF_LOG_SDK_PROTO_DATA_DIR` environment variable to enable writing individual data field files to disk. In the future, this may need to be offered as a server configuration so it can work better in conjunction with testing frameworks (e.g. `t.TempDir()`), but there should not be too much preventing that as a later enhancement as necessary.
Without `TF_LOG_SDK_PROTO_DATA_DIR` set (once):
```text
2022-01-06T16:04:54.787-0500 [TRACE] provider.terraform-provider-framework: Skipping protocol data file writing because no data directory is set. Use the TF_LOG_SDK_PROTO_DATA_DIR environment variable to …
```
> Implement protocol data logging

- .changelog/139.txt
- tfprotov5/tf5server/server.go
- tfprotov6/tf6server/server.go
Closes #106
The rationale for choosing this particular value and making it a constant, rather than configurable, is included in the code.
> Increase gRPC maximum message size send and receive limits to 256MB

- tftypes/object.go
Reference: https://github.com/hashicorp/terraform-plugin-go/issues/82
Reference: https://github.com/hashicorp/terraform-plugin-go/issues/83
Reference: https://github.com/hashicorp/terraform-plugin-go/issues/97
Reference: https://github.com/hashicorp/terraform-plugin-go/issues/128
> tftypes: Further document Object type OptionalAttributes field usage

- tfprotov5/tf5server/server.go
This resolves the bellow error message printed on provider startup:
```
2022/02/02 01:07:48 [ERROR] Error parsing provider name "": Invalid provider source string: The "source" attribute must be in the format "[hostname/][namespace/]name"
```
> Propagate provider name into GRPCProviderPlugin

- .github/dependabot.yml
Reference: https://github.com/hashicorp/terraform-providers-devex-internal/issues/79
Reference: https://github.com/hashicorp/terraform-plugin-sdk/blob/aeb1360e9c212819eefc4c5576eb513ad027af6e/.github/dependabot.yml#L9-L10
> .github: Add github-actions management to dependabot and ignore go-hclog

- tfprotov5/resource.go
- tfprotov6/resource.go
> tfprotov5+tfprotov6: Additional Go documentation for private state handling

- .changelog/213.txt
- tfprotov5/state.go
- tfprotov5/state_test.go
- tfprotov6/state.go
- tfprotov6/state_test.go
- tftypes/value_json.go
- tftypes/value_json_test.go
Closes: #212 
An error is generated when unmarshalling JSON that contains fields that do not have a corresponding attribute.
This PR adds an additional function, `UnmarshalWithOpts` that allows supplying of options that modify unmarshalling behaviour. Specifically, ignoring of undefined attributes is configurable.
> Allow ignoring undefined attributes during unmarshalling

- tfprotov5/internal/diag/diagnostics.go
- tfprotov5/internal/tf5serverlogging/downstream_request.go
- tfprotov6/internal/diag/diagnostics.go
- tfprotov6/internal/tf6serverlogging/downstream_request.go
- tftypes/value.go
To prevent issues with the latest `golangci-lint` in CI.
> all: Run Go 1.19 fmt

- go.mod
- go.sum
Updates `github.com/hashicorp/terraform-registry-address` to its first tagged release, `v0.1.0`, so tooling such as Dependabot will begin suggesting any updates.
Updated via:
```shell
go get github.com/hashicorp/terraform-registry-address@v0.1.0
go mod tidy
```
> deps: github.com/hashicorp/terraform-registry-address@v0.1.0

- .golangci.yml
- tfprotov5/dynamic_value.go
- tfprotov6/dynamic_value.go
- tftypes/attribute_path.go
- tftypes/diff.go
- tftypes/value.go
- tftypes/value_json.go
- tftypes/value_msgpack.go
contributes to: https://github.com/hashicorp/terraform-providers-devex-internal/issues/102 + https://github.com/hashicorp/terraform-providers-devex-internal/issues/83
- Tried to keep lint ignores consistent for the "type" [switches](https://github.com/hashicorp/terraform-plugin-go/pull/248/files#diff-4d63e5350ff3f5aacb2c53e6d245335b45e121735932a0b5025e14f8587886b8) by keeping them in the statement and not underlying functions
- `deadcode` and `varcheck` linters are deprecated in **golangci-lint** in favor of `unused`
```bash
$ golangci-lint run
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have …
```
> ci: added `forcetypeassert` and `misspell` lint rules 

- .changes/unreleased/NOTES-20230228-130401.yaml
- .github/workflows/ci-protobuf.yml
- README.md
- go.mod
- tfprotov5/internal/tfplugin5/tfplugin5.pb.go
- tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go
- tfprotov6/internal/tfplugin6/tfplugin6.pb.go
- tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go
Reference: https://github.com/hashicorp/terraform-plugin-go/issues/265
Bumped via:
```shell
go mod edit -go=1.19
go mod tidy
go fix ./...
```
> all: Bump minimum Go version to 1.19

- .changes/unreleased/ENHANCEMENTS-20230627-125806.yaml
- .changes/unreleased/ENHANCEMENTS-20230627-125912.yaml
- tfprotov5/dynamic_value.go
- tfprotov5/dynamic_value_test.go
- tfprotov6/dynamic_value.go
- tfprotov6/dynamic_value_test.go
> tfprotov5+tfprotov6: Add DynamicValue type IsNull method

- .changes/unreleased/BUG FIXES-20230630-103655.yaml
- .changes/unreleased/BUG FIXES-20230630-144701.yaml
- .changes/unreleased/BUG FIXES-20230630-144945.yaml
- .changes/unreleased/ENHANCEMENTS-20230630-143817.yaml
- tftypes/attribute_path.go
- tftypes/value.go
- tftypes/value_benchmark_test.go
- tftypes/value_equal.go
- tftypes/value_walk.go
- tftypes/walk.go
- tftypes/walk_benchmark_test.go
- tftypes/walk_test.go
Closes #307
These optimizations were performed by adding benchmark tests against a set of 1000 "simple" objects and viewing the cpu/memory profiles. The original implementations were spending an immense amount of time dealing with memory allocations and garbage collection, so reducing memory allocations was the main target of these optimizations, which in turn, also reduced compute time.
The largest changes were accomplished by removing `(Value).Diff()` from the logic paths which were only testing equality. The new `(Value).deepEqual()` implementation started as a duplicate of that logic, removing all `ValueDiff` allocations. Then, the walking of `Value` needed a methodology to stop the walk immediately to prevent further allocations. The two changes in that regard were introducing a …
> tftypes: Reduce AttributePath and Value type compute and memory usage

- tfprotov5/internal/toproto/attribute_path.go
- tfprotov5/internal/toproto/attribute_path_test.go
- tfprotov5/internal/toproto/data_source.go
- tfprotov5/internal/toproto/data_source_test.go
- tfprotov5/internal/toproto/diagnostic.go
- tfprotov5/internal/toproto/diagnostic_test.go
- tfprotov5/internal/toproto/function.go
- tfprotov5/internal/toproto/function_test.go
- tfprotov5/internal/toproto/provider.go
- tfprotov5/internal/toproto/provider_test.go
- tfprotov5/internal/toproto/resource.go
- tfprotov5/internal/toproto/resource_test.go
- tfprotov5/tf5server/server.go
- tfprotov6/internal/toproto/attribute_path.go
- tfprotov6/internal/toproto/attribute_path_test.go
- tfprotov6/internal/toproto/data_source.go
- tfprotov6/internal/toproto/data_source_test.go
- tfprotov6/internal/toproto/diagnostic.go
- tfprotov6/internal/toproto/diagnostic_test.go
- tfprotov6/internal/toproto/function.go
- tfprotov6/internal/toproto/function_test.go
- tfprotov6/internal/toproto/provider.go
- tfprotov6/internal/toproto/provider_test.go
- tfprotov6/internal/toproto/resource.go
- tfprotov6/internal/toproto/resource_test.go
- tfprotov6/tf6server/server.go
Reference: https://github.com/hashicorp/terraform-plugin-go/issues/365
It is not possible for an unexpected attribute path step implementation to reach the protocol conversion logic unless there is a protocol change, which the logic should be updated anyways at the same time and unit tested. This simplifies many of the gRPC server handling methods to not need to handle the currently impossible-to-have errors.
> tfprotov5+tfprotov6: Remove unnecessary AttributePath_Step error return

- .changes/unreleased/BUG FIXES-20240418-121811.yaml
- CHANGELOG.md
- tftypes/value_msgpack.go
- tftypes/value_msgpack_test.go
Round-tripping a large integer through a float64, even if the binary representation is exact, causes us to end up with a rounded string representation after decoding, because the decoded number has 52-bit precision instead of the 512 we use when dealing with string representations of large integers.
The test fixture was changed slightly to compare only the final value string representations, which more closely corresponds to the configuration and state values. The comparison of the `Value` directly will contain differences in the underlying `math/big` value.
This mirrors the upstream change in go-cty [here](https://github.com/zclconf/go-cty/commit/f41ae52fdfa8a9590aa00c3ab3ff13cef4dd872f), which will be incorporated into the next version of Terraform, ensuring that the round-trip encoding …
> don't marshal integer values as msgpack floats

- .changes/unreleased/BREAKING CHANGES-20240510-105824.yaml
- .changes/unreleased/NOTES-20240510-105942.yaml
- tfprotov5/resource.go
- tfprotov6/resource.go
Closes #389
The `ResourceServerWithMoveResourceState` temporary interface was introduced as a way to onboard downstream SDKs onto the new `MoveResourceState` RPC before it was required. This enabled a period where terraform-plugin-go could support new functionality while not causing compilation errors if downstream Go modules happened to be referencing differing SDK versions that may or may not all support the new functionality immediately. Now that those downstream Go modules are referencing `ResourceServer` directly again, the temporary interface can be removed to prevent bloating this Go module.
> tfprotov5+tfprotov6: Remove temporary ResourceServerWithMoveResourceState interface

- .changes/unreleased/FEATURES-20250210-175144.yaml
- .changes/unreleased/NOTES-20250210-175414.yaml
- tfprotov5/provider.go
- tfprotov6/internal/fromproto/provider.go
- tfprotov6/internal/fromproto/provider_test.go
- tfprotov6/internal/fromproto/raw_identity.go
- tfprotov6/internal/fromproto/raw_identity_test.go
- tfprotov6/internal/fromproto/resource.go
- tfprotov6/internal/fromproto/resource_identity_data.go
- tfprotov6/internal/fromproto/resource_identity_data_test.go
- tfprotov6/internal/fromproto/resource_test.go
- tfprotov6/internal/toproto/provider.go
- tfprotov6/internal/toproto/provider_test.go
- tfprotov6/internal/toproto/resource.go
- tfprotov6/internal/toproto/resource_identity_data.go
- tfprotov6/internal/toproto/resource_identity_data_test.go
- tfprotov6/internal/toproto/resource_identity_schema.go
- tfprotov6/internal/toproto/resource_identity_schema_test.go
- tfprotov6/internal/toproto/resource_test.go
- tfprotov6/provider.go
- tfprotov6/raw_identity.go
- tfprotov6/raw_identity_test.go
- tfprotov6/resource.go
- tfprotov6/resource_identity_data.go
- tfprotov6/resource_identity_schema.go
- tfprotov6/tf6server/server.go
shamelessly copied from protocol v5 as merged via #474
differences to the other PR:
* this PR uses `v6` where the other used `v5`
* the server.go for `v6` was in a sub directory
This PR also adds two changie entries for this change and the two related ones that already landed
> tfprotov6: Resource Identity implementation

- .changes/unreleased/FEATURES-20250307-153800.yaml
- tfprotov5/tf5server/server.go
- tfprotov6/tf6server/server.go
This PR introduces the option to write the `TF_REATTACH_PROVIDERS` environment variable (and its value) into a file that can be used by downstream tooling.
For example, it can be used in a VSCode launch configuration for debugging Terraform, which allows to debug both provider and Terraform at the same time without the constant need to change `TF_REATTACH_PROVIDERS` in Terraform's debug configuration:
> feat: Add `WithManagedDebugEnvFilePath()` option that allows writing `TF_REATTACH_PROVIDERS` to an environment file

- tfprotov5/resource_identity_schema.go
- tfprotov5/resource_identity_schema_test.go
- tfprotov6/resource_identity_schema.go
- tfprotov6/resource_identity_schema_test.go
Adds the `(*ResourceIdentitySchema).ValueType()` and `(*ResourceIdentitySchemaAttribute).ValueType()` implementations to retrieve the relevant `tftypes.Type`.
This can be useful for decoding dynamic values like we do in the `testprovider`  implementation in `terraform-plugin-testing`: https://github.com/hashicorp/terraform-plugin-testing/pull/468/files#diff-4a86857e52f10a46f3a385f0dc7eed824866ff9d6edbe23c0fb4aa09b1156394
> tfprotov5+6: Add `ValueType` implementation to identity schemas

- .changes/unreleased/BREAKING CHANGES-20250521-145243.yaml
- .changes/unreleased/BREAKING CHANGES-20250521-145326.yaml
- .changes/unreleased/NOTES-20250521-145307.yaml
- tfprotov5/provider.go
- tfprotov5/resource.go
- tfprotov5/tf5server/server.go
- tfprotov6/provider.go
- tfprotov6/resource.go
- tfprotov6/tf6server/server.go
Closes https://github.com/hashicorp/terraform-plugin-go/issues/478
This PR removes the `ProviderServerWithResourceIdentity` temporary interface, which was causing issues with providers not implementing it fully via muxed providers or when implementing a plugin-go server, since Terraform v1.12.1 will call `GetResourceIdentitySchemas` even if the provider doesn't support identity (GRPC unimplemented codes keep older providers from failing)
N/A
> all: Remove temporary `ProviderServerWithResourceIdentity` interface

- tfprotov5/list_resource.go
- tfprotov5/tf5server/server.go
- tfprotov6/list_resource.go
- tfprotov6/tf6server/server.go
This change adds an exported `NoListResults` variable to the `tfprotov5` and `tfprotov6` packages. This is a syntactic convenience to be used by SDKs as a default value.
No
> Add `tfprotov{5,6}.NoListResults` for convenience

- .changes/0.29.0-alpha.1.md
- .changes/unreleased/NOTES-20250703-163629.yaml
- .changes/unreleased/NOTES-20250703-163637.yaml
- .changes/unreleased/NOTES-20250703-163653.yaml
- .changes/unreleased/NOTES-20250703-163708.yaml
- CHANGELOG.md
Reverts hashicorp/terraform-plugin-go#535, because the Release action wants to run `changie batch` for us.
> Revert "Update CHANGELOG.md"

- tfprotov5/action.go
- tfprotov5/internal/fromproto/action.go
- tfprotov5/internal/fromproto/actions_test.go
- tfprotov5/internal/tfplugin5/tfplugin5.pb.go
- tfprotov5/internal/tfplugin5/tfplugin5.proto
- tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go
- tfprotov5/internal/toproto/action.go
- tfprotov5/internal/toproto/action_test.go
- tfprotov5/tf5server/server.go
- tfprotov6/action.go
- tfprotov6/internal/fromproto/action.go
- tfprotov6/internal/fromproto/actions_test.go
- tfprotov6/internal/tfplugin6/tfplugin6.pb.go
- tfprotov6/internal/tfplugin6/tfplugin6.proto
- tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go
- tfprotov6/internal/toproto/action.go
- tfprotov6/internal/toproto/action_test.go
- tfprotov6/tf6server/server.go
N/A
This PR introduces a `ValidateActionConfig` RPC for usage with `terraform validate` for offline validation of action configuration, similar to other types.
This PR also adjusts the field numbering of `GetProviderSchema` / `GetMetadata` to match what is in Terraform core ATM. Ref:
- https://hashicorp.slack.com/archives/CKJV0JLRX/p1752749473252709
- https://github.com/hashicorp/terraform/blob/7199fbd2bb91284edd078ff37693574fb8b0dd71/docs/plugin-protocol/tfplugin6.proto#L499
No
> tfprotov5+tfprotov6: Add action validation RPC + fix proto field numbering

- tfprotov6/state_store.go
- tfprotov6/tf6server/server.go
N/A
This PR updates `WriteStateBytes`'s implementation so that users can receive any gRPC errors that arose when receiving state data from Terraform core. This allows provider implementations to have custom logic for handling errors that might happen partway though streaming in state data (clean up, etc).
Alternative solutions can be seen in the commit history - we explored using iter.Seq2 but instead decided to use iter.Seq with a struct that contains multiple pieces of information. This follows a pattern already used in terraform-exec and means consumers of terraform-plugin-go benefit from the named fields and any associated go doc comments when understanding the contents of the streamed message.
None
> Sarah's updates to f-pluggable-state-store
