tfprotov5/server/doc.go

A minor change to the tf5server package to improve readability.

Update tf5server package documentation language

---

.changelog-note.tmpl
.changelog.tmpl

These templates can be used with changelog-build to generate changelogs
from the .changelog directory.

Add go-changelog-gen templates.

---

tftypes/value_json.go
tftypes/value_msgpack.go

Our JSON/MsgPack parsing code still used the pre-#68 AttributePath,
passing them by Value, which was doing unnecessary work and wouldn't
yield correct paths for complex types. Changing it to the new style does
less work and yields correct paths.
Blocked on #77 merging, should have its diff recalculated once that merges.

Fix AttributePaths when parsing JSON/MsgPack.

---

tftypes/attribute_path_test.go

Add unit tests for AttributePath.String()

---

.github/workflows/ci-go.yml

.github/workflows: Add terraform-provider-corner acceptance testing to Go CI

---

.github/workflows/ci-go.yml
go.mod
go.sum
internal/logging/provider.go

Depends on https://github.com/hashicorp/terraform-registry-address/pull/12

Switch to the new minimal terraform-registry-address API

---

.github/workflows/ci-go.yml

Reference: https://github.com/hashicorp/terraform/releases/tag/v1.3.0

.github/workflows: Add Terraform 1.3.x to testing matrix

---

tfprotov5/internal/tfplugin5/tfplugin5.pb.go
tfprotov5/internal/tfplugin5/tfplugin5.proto
tfprotov6/internal/tfplugin6/tfplugin6.pb.go
tfprotov6/internal/tfplugin6/tfplugin6.proto

Reference: https://github.com/hashicorp/terraform/pull/31998

tfprotov5+tfprotov6: Synchronize Protocol Buffers comments for ReadResource and UpgradeResourceState

---

.github/workflows/add-content-to-project.yml
.github/workflows/ci-github-actions.yml
.github/workflows/ci-go.yml
.github/workflows/ci-goreleaser.yml
.github/workflows/ci-protobuf.yml
.github/workflows/release.yml

Reference: https://github.com/hashicorp/terraform-providers-devex-internal/issues/118

.github/workflows: Pin actions versions to SHAs

---

.golangci.yml
tfprotov5/internal/toproto/diagnostic_test.go
tfprotov6/internal/toproto/diagnostic_test.go
tftypes/primitive_test.go
tftypes/type_json_test.go
tftypes/value_test.go
tftypes/walk_test.go

contributes to:
- https://github.com/hashicorp/terraform-providers-devex-internal/issues/126

ci: unleash the `paralleltest` lints

---

.changes/unreleased/BUG FIXES-20230616-153754.yaml
tfprotov6/tf6server/server.go

Ref: https://github.com/hashicorp/terraform-plugin-framework/issues/781

Fix StopProvider RPC function call in v6

---

.github/workflows/ci-go.yml

At some point we'll switch the CI workflows to using GitHub Actions shared configuration variables.

ci: Test with Terraform 1.6.x

---

.changes/unreleased/NOTES-20231115-091528.yaml

After merge, will cut a bug fix release.

Update CHANGELOG for #324

---

tfprotov5/internal/tfplugin5/tfplugin5.pb.go
tfprotov5/internal/tfplugin5/tfplugin5.proto
tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go
tfprotov5/tf5server/server.go
tfprotov6/internal/tfplugin6/tfplugin6.pb.go
tfprotov6/internal/tfplugin6/tfplugin6.proto
tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go
tfprotov6/tf6server/server.go

Ref #478
This reverts commit f412d3942e55695a3afac20f7f2862ba4bfb4d00. There isn't anything wrong with this specific commit, but we are planning on resolving #478 soon and would like to release it without the recent RPC changes.
Result of:
```bash
git revert f412d3942e55695a3afac20f7f2862ba4bfb4d00
```
N/A

Revert "Add protobuf support for list messages and rpcs (#512)"

---

.github/CONTRIBUTING.md

Ref: https://github.com/hashicorp/terraform-plugin-framework/issues/1148
Adds some contributing docs to talk about temporary interfaces and how we can use them. Any feedback/questions are welcome!
N/A

Add maintainer note about temporary interfaces for new RPCs

---

examples/terraform-provider-primes/provider.go

This pull request updates the `primes` example provider for compatibility with the latest Terraform v1.13.0 alpha pre-release. Resource identity data is required.
None

primes: include resource identity data in list results

---

.changes/unreleased/BUG FIXES-20250731-164517.yaml
.changes/unreleased/FEATURES-20250731-164424.yaml
.changes/unreleased/NOTES-20250731-164317.yaml

Changelog for v.0.29.0-beta.1
None

Add Changelog

---

tfprotov5/action.go
tfprotov6/action.go

N/A
Just a quick doc fix 😆 
No

Fix grammar in package docs 😅

---

.changes/unreleased/ENHANCEMENTS-20250916-104411.yaml
.changes/unreleased/FEATURES-20250916-105029.yaml
.changes/unreleased/NOTES-20250916-105140.yaml

N/A
Prepping the repo for `v0.29.0` release, this PR has changelogs for the action related work and the one miscellaneous PR that had a changelog in one of the pre-releases (#541).
No

actions: Add action changelogs + misc changelog from pre-release

---

.changes/unreleased/FEATURES-20250917-081456.yaml

List changelog entry for `v0.29.0`
Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.
None.

list: add changelog
